region              = "us-east-2"
aws_account_id      = "123456789012"
vpc_name            = "eks-vpc"
vpc_cidr            = "10.0.0.0/16"
availability_zones  = ["us-east-2a", "us-east-2b"]
public_subnets      = ["10.0.1.0/24", "10.0.2.0/24"]
cluster_name        = "fraud-detection-cluster"
node_group_name     = "eks-node-group"
node_instance_type  = "t3.medium"
desired_capacity    = 1
min_size            = 1
max_size            = 1
ecr_repo_name       = "fraud_detection"
