apiVersion: v1
kind: Service
metadata:
  name: fraud-detection
spec:
  type: {{ .Values.service.type }}
  selector:
    app: fraud-detection
  ports:
    - protocol: TCP
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
